# Generated by Django 6.1.1 on 2026-09-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('principio_activo', models.CharField(max_length=150)),
                ('lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('precio_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_bodega', models.PositiveIntegerField(default=0, help_text='Cantidad física en bodega')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='inventory.categoria')),
            ],
        ),
    ]
