# Generated by Django 5.0.14 on 2026-09-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Campo para borrado lógico (activar/desactivar)'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Campo para borrado lógico (activar/desactivar)'),
        ),
    ]
